"""Structured, layman-friendly companion to the paper (paper/main.tex).

Each section holds a list of blocks. A block pairs a short verbatim quote from
the paper (`q`) with a plain-English explanation (`p`). This drives the
"Paper, Explained" page so every line of the paper can be narrated in simple
language during the CHANDICON talk.

Sources: paper/main.tex (quotes) + paper/PAPER_EXPLAINED.md (plain wording).
"""

PAPER_TITLE = "Urban Expansion Monitoring Using Transfer Learning on Historical Satellite Imagery"
VENUE = "Accepted — IEEE CHANDICON 2026"
AUTHORS = "Kaustubh Agarwal, Prajwal Gupta, Kabir Rai, P Manideep Reddy, Naman Khurana, Dr. Divyashree N — PES University, Bengaluru"

SECTIONS = [
    {
        "id": "abstract",
        "number": "0",
        "title": "Abstract",
        "summary": "The 30-second version of the whole paper.",
        "blocks": [
            {"q": "Uncontrolled urban expansion in Indian metropolitan regions accelerates encroachment on legally protected zones, yet existing studies rely on single-city, single-seed SVM/RF benchmarks without downstream forecasting or alerting.",
             "p": "Indian cities are growing fast and eating into protected forests, wetlands and coasts. But past research only used old-school methods (SVM/Random Forest) on one city at a time, and never predicted future growth or raised alerts. Nobody built a complete system."},
            {"q": "We propose an end-to-end framework integrating transfer-learning classification, SAR–optical fusion, self-supervised pre-training, uncertainty-aware Bi-LSTM forecasting, and regulatory encroachment alerting.",
             "p": "We built one connected pipeline with five parts: (1) classify land using AI, (2) combine optical + radar images, (3) try learning from unlabelled images, (4) forecast future growth with confidence bands, and (5) automatically flag illegal construction."},
            {"q": "A benchmark of 2,730 Sentinel-2 patches across Mumbai, Delhi NCR, and Bangalore with a novel three-class taxonomy (Urban, Non-Urban, Transition) is constructed from ESA WorldCover 2021.",
             "p": "We made a dataset of 2,730 small satellite image tiles from 3 cities. Each tile is labelled Urban, Non-Urban, or Transition (the messy edge where a city is actively spreading), using a free global land-cover map as the answer key."},
            {"q": "Six model families ... are trained with three-stage progressive fine-tuning and a combined CE–focal–Dice loss across three random seeds.",
             "p": "We tested 6 models. The deep-learning ones are trained gradually in 3 stages, and everything is run 3 times with different random starts so the results aren't a fluke."},
            {"q": "ResNet50 achieves 97.5 ± 0.2% overall accuracy (OA), surpassing the best published Indian SVM (91.01%) by six points.",
             "p": "Our best model gets 97.5% of tiles right — about 6 points better than the best previously published Indian result."},
            {"q": "The first Leave-One-City-Out (LOCO) benchmark for Indian metros reveals a 15–20% cross-city accuracy drop and a CNN–Transformer ranking reversal where Swin-Tiny (79.1 ± 3.9%) generalizes better than ResNet50 (77.1 ± 5.1%).",
             "p": "When we train on 2 cities and test on a city the model has never seen, accuracy drops ~18%. Surprise finding: the Transformer model (Swin) handles unseen cities better than the CNN (ResNet50), even though ResNet50 was better on familiar cities."},
            {"q": "The pipeline produces uncertainty-calibrated 2024–2035 forecasts and, in a seven-city encroachment simulation, generates 55 simulated alerts with rule-based routing to the appropriate Indian regulatory authority.",
             "p": "The system predicts each city's growth to 2035 with 'how sure are we' bands, and in a simulation it raised 55 encroachment alerts, each automatically sent to the right government body."},
        ],
    },
    {
        "id": "intro",
        "number": "I",
        "title": "Introduction — the problem & what's new",
        "summary": "Why this matters, and the 7 things this paper adds.",
        "blocks": [
            {"q": "India's urban population is projected to exceed 600 million by 2031, with major metropolitan regions already expanded two- to four-fold in built-up area since 1990.",
             "p": "By 2031, 600 million Indians will live in cities, and the big metros have already doubled-to-quadrupled in built-up size since 1990. That scale of change can't be tracked by walking around on the ground."},
            {"q": "encroachment on legally protected zones continues despite the Coastal Regulation Zone Notification 2019, the Forest Conservation Act 1980, and the Wetland Rules 2017.",
             "p": "Problem 1: despite strong laws, people keep building illegally in forests, wetlands and coastal zones (e.g. Sanjay Gandhi NP in Mumbai, Bellandur wetland in Bangalore, Yamuna floodplain in Delhi)."},
            {"q": "infrastructure planning ignores uncertainty—point forecasts offer no confidence bounds, causing capital misallocation.",
             "p": "Problem 2: planners forecast a single growth number with no error bars, so they over- or under-build infrastructure and waste money."},
            {"q": "deep learning is under-used for Indian urban classification ... published Indian urban studies rely overwhelmingly on single-city SVM/RF pipelines reaching only 89–91% OA, with no cross-city evaluation and no link from classification to forecasting or alerting.",
             "p": "Problem 3: modern AI gets 97%+ on European satellite data, but Indian studies still use basic methods stuck at 89–91%, never test across cities, and never connect classification to prediction or alerts."},
            {"q": "what is missing is an integrated pipeline from raw Indian imagery to policy-actionable output.",
             "p": "The satellite data already exists for free. What's missing is one system that goes from raw images all the way to something a policymaker can act on. That's the gap we fill."},
            {"q": "Multi-city Indian urban expansion benchmark with the first LOCO evaluation for Indian metros.",
             "p": "Contribution 1: a proper multi-city Indian dataset + the first ever 'train on some cities, test on a held-out city' benchmark for India."},
            {"q": "Progressive fine-tuning achieving 97.5 ± 0.2% OA on real Indian data without any domain-specific pre-training.",
             "p": "Contribution 2: a careful 3-stage training recipe that hits 97.5% using only standard ImageNet-pretrained models — no exotic satellite pretraining needed."},
            {"q": "Novel Transition class via morphological dilation of urban boundaries (100 m buffer).",
             "p": "Contribution 3: a new third class, 'Transition', drawn as a 100m band around city edges — exactly where the mixed, ambiguous, actively-growing pixels are."},
            {"q": "Uncertainty-aware Bi-LSTM forecasting producing 95% Monte-Carlo-Dropout confidence intervals on 2024–2035 urban-area forecasts.",
             "p": "Contribution 4: forecasts that come with 95% confidence bands — no published Indian forecasting study does this."},
            {"q": "First weak-supervision-to-policy-action pipeline ... classify → time series → forecast → regulatory alert.",
             "p": "Contribution 5: the first end-to-end chain for India — classify, build a growth timeline, forecast, then raise an alert routed to the correct authority (encoding 10 zone types and 30+ named protected areas)."},
            {"q": "CNN–Transformer ranking reversal under cross-city transfer.",
             "p": "Contribution 6: the discovery that the best model flips depending on the test — ResNet50 wins on known cities, Swin-Tiny wins on unknown ones."},
            {"q": "Transparent negative-result reporting for SAR fusion, SimCLR pre-training, and FPN ablation.",
             "p": "Contribution 7: we honestly report the things that DIDN'T help (radar fusion, self-supervised pretraining, the FPN module) instead of hiding them — which builds trust."},
        ],
    },
    {
        "id": "litreview",
        "number": "II",
        "title": "Literature Survey — what others did",
        "summary": "16 prior works, and the exact gap we fill.",
        "blocks": [
            {"q": "On EuroSAT, ResNet50, EfficientNet, and ViT reach 96.78–98.57% OA, but transferability to Indian imagery is unexplored.",
             "p": "On the standard European benchmark, modern models already score 96–98%. But nobody checked whether that carries over to messier Indian cities."},
            {"q": "Indian urban classification is dominated by SVM/RF (best: 91.01%); binary single-region ensembles reach 98.21% but none perform multi-city LOCO analysis.",
             "p": "The best published Indian classical-ML result is 91%. One study hits 98% but only does easy 2-class labelling on a single region — and none test across cities like we do."},
            {"q": "a 2025 review of 89 S2 studies report 15–25% deploy gaps; our 18% confirms this for Indian metros.",
             "p": "A big review of 89 studies found accuracy drops 15–25% when a model meets new real-world areas. Our 18% cross-city drop matches that — independent validation of our number."},
            {"q": "transformers outperform CNNs OOD while CNNs win on small datasets—consistent with our reversal.",
             "p": "Known theory: Transformers handle 'out-of-distribution' (unfamiliar) data better, but CNNs win on small datasets. Our results show both effects at once."},
            {"q": "no published work connects, for Indian metros, multi-seed DL classification, LOCO generalization, uncertainty-aware forecasting, and regulatory alerting in a single pipeline.",
             "p": "The gap in one sentence: nobody has put all four pieces together for Indian cities. That combination is our contribution."},
        ],
    },
    {
        "id": "dataset",
        "number": "III",
        "title": "Dataset Construction — the data",
        "summary": "Where the images come from and how they're labelled.",
        "blocks": [
            {"q": "Three Indian metropolitan archetypes are selected: Mumbai (coastal megacity ...), Delhi NCR (radial sprawl ...), and Bangalore (IT-corridor city ...).",
             "p": "We picked 3 cities with very different growth shapes: Mumbai (squeezed by the sea), Delhi NCR (spreads outward like a circle), Bangalore (scattered IT-park pockets)."},
            {"q": "Sentinel-2 L2A (10 m, 6 bands ..., SCL cloud-masked, pre-monsoon composites) serves as the primary classification input.",
             "p": "Main input: free Sentinel-2 satellite images at 10m/pixel, with clouds removed, taken in the dry pre-monsoon season (clearest skies in India)."},
            {"q": "Sentinel-1 SAR ... is used for the fusion experiment; Landsat 5/7/8/9 ... provides historical anchors for the Bi-LSTM forecaster only.",
             "p": "Radar (SAR) images are only used for the fusion test. Older Landsat images (back to 1990) are only used to build the long-term growth timeline, not for the main classifier."},
            {"q": "256×256 patches are extracted ..., producing 2,730 optical patches and 910 co-located SAR patches. The dataset is split 70/15/15 ... with three additional LOCO folds.",
             "p": "We cut the big images into 2,730 small 256×256 tiles (910 also have radar). We use 70% to train, 15% to tune, 15% to test — plus 3 special splits where a whole city is held out."},
            {"q": "Labels — derived via weak supervision from ESA WorldCover 2021 ..., cross-validated against Google Dynamic World.",
             "p": "The 'correct answers' come automatically from a free global land-cover map (not hand-drawn by people), and we double-check against a second map."},
            {"q": "Transition (100 m morphological dilation of Urban boundaries—novel for Indian urban studies, absorbing mixed-pixel ambiguity at the active expansion interface).",
             "p": "Our new 'Transition' class is a 100m band painted around every urban edge. At 10m resolution those edge pixels are half-building, half-field — Transition gives them an honest home instead of forcing a wrong label."},
            {"q": "class distribution: Urban 19.2%, Non-Urban 62.4%, Transition 18.4%.",
             "p": "Most tiles are Non-Urban (62%); Urban and Transition are about 19% each. Transition being the rarest is why we give it extra weight during training."},
        ],
    },
    {
        "id": "method",
        "number": "IV",
        "title": "Proposed Methodology — how it works",
        "summary": "The models, the training recipe, the loss, and the pipeline.",
        "blocks": [
            {"q": "Four deep backbones (all ImageNet-pretrained) are evaluated alongside SVM and Random Forest: ResNet50 (11.3M, primary), EfficientNet-B0 (5.3M ...), Swin-Tiny (29.8M ...), MobileNetV3-Small (3.4M, edge deployment).",
             "p": "We compare 4 deep models (each already trained on millions of everyday photos) plus 2 classic baselines. ResNet50 is the main one; MobileNetV3 is the tiny one for phones/edge devices."},
            {"q": "A three-level FPN at strides 4/8/16 is upsampled and concatenated before the classifier head.",
             "p": "An 'FPN' lets the model look at the image at three zoom levels at once — fine details (buildings) and big patterns (neighbourhoods) together — before deciding."},
            {"q": "Stage 1 trains the head only (5 epochs, lr 1e-3), Stage 2 unfreezes the last two backbone blocks (lr 1e-4), and Stage 3 fine-tunes the full network (lr 1e-5).",
             "p": "Progressive fine-tuning: first teach only the final decision layer, then unlock the last couple of layers, then gently adjust the whole network. This avoids wrecking the useful knowledge the model already had."},
            {"q": "L = 0.6·L_CE + 0.3·L_Focal(γ=2) + 0.1·L_Dice. ... Class weights [1.0, 1.0, 3.0] upweight the minority Transition class.",
             "p": "The 'loss' (the thing the model tries to minimise) blends 3 ingredients: a standard one, one that focuses on hard examples, and one that protects rare classes. The rare Transition class is weighted 3× so it isn't ignored."},
            {"q": "A dual-branch encoder processes 6-channel optical and 2-channel SAR inputs separately; feature maps are concatenated before the shared FPN head.",
             "p": "For the radar-fusion test, optical and radar images go through two separate mini-networks, then their features are glued together before the final decision."},
            {"q": "SimCLR contrastive pre-training is run on unlabeled Indian patches ... and then fine-tuned with the progressive strategy.",
             "p": "For the self-supervised test, the model first learns from unlabelled images by matching two augmented copies of the same tile, before normal training."},
            {"q": "The forecasting module is a bidirectional LSTM with residual connections, LayerNorm, 2-head temporal attention, and Monte-Carlo Dropout (p = 0.2) yielding 94K parameters.",
             "p": "The forecaster is a small recurrent network that reads the growth timeline both forwards and backwards. 'MC Dropout' means we run it 50 times with bits randomly switched off, and the spread of answers becomes the confidence band."},
            {"q": "a three-head change detector then classifies each patch for (i) change / no-change, (ii) severity ..., and (iii) encroachment type, encoding ten India-specific regulatory zone types ... alerts are auto-routed to MoEFCC, CZMA, or the State Forest Department.",
             "p": "The alert engine decides three things per tile: did it change? how serious? what type? It knows 10 Indian protected-zone types and sends each alert to the correct authority (environment ministry, coastal authority, or forest dept)."},
            {"q": "the integrated pipeline slides a 256×256 window over each GeoTIFF, counts Urban pixels to build the city-year area series ..., runs fifty MC-Dropout forward passes ..., intersects each forecast zone with the regulatory database, and routes each alert.",
             "p": "Putting it together: slide a window across the big image, count urban pixels per year to get a growth curve, forecast forward with confidence bands, check the predicted growth against protected zones, and fire off routed alerts."},
        ],
    },
    {
        "id": "results",
        "number": "V",
        "title": "Results & Discussion — what we found",
        "summary": "The headline numbers and what they mean.",
        "blocks": [
            {"q": "ResNet50 wins on every metric and has the lowest seed variance, indicating both accuracy and stability, significantly outperforming MobileNetV3-Small (p = 0.038).",
             "p": "ResNet50 is both the most accurate (97.5%) and the most consistent across random restarts. Its win over the tiny MobileNet is statistically real (not luck)."},
            {"q": "the improved-SVM (92.6 ± 1.4%) surpasses the best published Indian SVM—all three seeds exceed 91.01%—while trailing ResNet50 by ∼5 points, establishing a hard ceiling for traditional ML.",
             "p": "Even after we super-tuned the old-school SVM (it beats the best published one), deep learning still wins by 5 points. So this is a fair fight, not a rigged weak baseline."},
            {"q": "Our 97.5% OA is within 0.7 points of the highest published Indian result—IRUNet at 98.21%—despite being harder (3-class, multi-city, LOCO).",
             "p": "The one Indian result above us (98.2%) solves an easier problem (2 classes, one region). We're within 0.7 points on a much harder 3-class, multi-city task."},
            {"q": "a CNN–Transformer ranking reversal: ResNet50 drops 20.4% (97.5%→77.1%) under LOCO while Swin-Tiny drops only 14.5% (93.6%→79.1%).",
             "p": "The key plot twist: on a brand-new city, ResNet50 collapses by 20 points but Swin only by 14, so Swin ends up ahead. CNNs memorise city-specific textures; the Transformer learns more general 'what a city looks like'."},
            {"q": "Delhi NCR is the hardest held-out target (71.8–76.7%) ..., while Bangalore is the easiest (80.4–83.9%) despite being the hardest in-distribution city—a separation between local ambiguity and cross-city domain shift that is itself a novel finding.",
             "p": "Subtle finding: the city that's hardest to learn locally (Bangalore) is actually the easiest to transfer TO, while Delhi is the hardest to transfer to. 'Hard to learn' and 'hard to generalise to' are two different things."},
            {"q": "FPN adds +0.3 OA points, dominated by Transition-class boundaries. CE-only's 0.4-point OA advantage over the full method is not statistically significant (p=0.71); ... the full method achieves Transition F1 = 0.98.",
             "p": "Ablation honesty: the FPN helps only a little overall (mostly on edges), and plain loss looks 0.4 points higher but that's noise. We keep the fancy loss because it nails the rare Transition class (F1 0.98)."},
            {"q": "SAR–optical fusion underperforms optical-only because only 33% of patches have paired SAR and the available SAR is post-monsoon vs. pre-monsoon optical; this is a deliberately reported negative result.",
             "p": "Adding radar HURT (87.9% vs 96.7%) because only a third of tiles had radar and the seasons didn't match. We report it honestly — the lesson is 'don't add radar unless the timing lines up'."},
            {"q": "At our label budget (2,730 patches), ImageNet transfer beats SimCLR, whose advantage emerges mainly under <500 labels.",
             "p": "Self-supervised pretraining (SimCLR) also lost (93.2% vs 96.9%). With enough labels, plain ImageNet transfer is already better. SimCLR only pays off when you have very few labels."},
            {"q": "ResNet50 offers the best accuracy–latency balance (5.02 ms, 199 patches/s, 83 MB); MobileNetV3-Small is the edge-device model at 30.5 MB; Swin-Tiny is heaviest but most transferable.",
             "p": "Speed/size: ResNet50 is surprisingly the fastest and most accurate on our GPU; MobileNet is smallest for edge devices; Swin is the heaviest but travels best to new cities."},
            {"q": "The Bi-LSTM ... reaches R2 = 0.9564 ... With only four real satellite anchor years, R2 drops to 0.559 vs. Ridge (R2 = 0.601). The LSTM's key advantage is uncertainty quantification.",
             "p": "On clean data the forecaster is great (R²=0.96). On only-real-satellite data it's weaker than a simple linear model — but its real value is the confidence bands a linear model can't give."},
            {"q": "a seven-city simulation produces 55 simulated alerts (4 CRITICAL, 28 HIGH, 2 MED, 21 LOW) and 11 protected-zone violations, with critical alerts near Sanjay Gandhi NP and Pallikaranai marsh routed to MoEFCC.",
             "p": "The alert simulation flagged 55 events — 4 critical, 11 near protected zones — including hotspots by Sanjay Gandhi National Park and Pallikaranai marsh, each routed to the right ministry."},
            {"q": "Applied without retraining to 2019 and 2023 Sentinel-2, the 2021-trained ResNet50 estimates Mumbai's urban extent at 1,161 and 1,451 km2 (+25%, consistent with coastal construction).",
             "p": "A model trained only on 2021 still gives sensible answers on 2019 and 2023 images — Mumbai grew ~25% over that span, matching known coastal construction. So it generalises across time, not just space."},
        ],
    },
    {
        "id": "conclusion",
        "number": "VI",
        "title": "Conclusion, Limitations & Ethics",
        "summary": "What we proved, what we admit, and the responsible-use note.",
        "blocks": [
            {"q": "We presented an end-to-end Indian urban expansion framework unifying classification, fusion, self-supervision, Bi-LSTM forecasting, and regulatory alerting.",
             "p": "Bottom line: one connected system that takes Indian satellite images all the way to routed encroachment alerts."},
            {"q": "The study is currently limited to three Tier-1 cities, WorldCover weak labels, a dilated Transition class, calibrated socio-economic forecasting inputs, simulation-based alerts, and seasonally mismatched SAR.",
             "p": "We're upfront about limits: only 3 big cities, auto-generated (not hand-checked) labels, a rule-drawn Transition class, partly-calibrated forecast inputs, simulated (not field-verified) alerts, and mismatched radar seasons."},
            {"q": "Ethical considerations: alerts are advisory; human-in-the-loop verification is required to avoid disparate impact on informal settlements.",
             "p": "Responsibility note: these alerts are advisory only. A human must verify before any action, so the system isn't used to unfairly target informal settlements/slums."},
            {"q": "Future work: We plan to expand to Tier-2/3 cities, validate alerts against ground-truth municipal records, and improve SAR fusion via strict temporal alignment.",
             "p": "Next: add smaller cities, check alerts against real municipal records, and fix the radar fusion by aligning seasons properly."},
        ],
    },
    {
        "id": "repro",
        "number": "App. I",
        "title": "Reproducibility",
        "summary": "Everything needed to rerun the work.",
        "blocks": [
            {"q": "Python 3.11, PyTorch 2.0.1+cu118, ... timm 0.9.12 ...; NVIDIA RTX 4070 Laptop GPU (8 GB VRAM) ...; Seeds {42, 123, 7}; CUDA determinism enabled.",
             "p": "We list the exact software versions, the exact GPU, and the exact random seeds so anyone can reproduce our numbers."},
            {"q": "code and data at https://github.com/kaustubhagarwal21/urban-expansion-monitoring (upon acceptance).",
             "p": "All code and data will be public on GitHub on acceptance — reviewers can check everything."},
        ],
    },
]

GLOSSARY = [
    {"t": "Transfer learning", "p": "Take a model already trained on millions of everyday photos and adapt it to satellite images instead of starting from zero."},
    {"t": "Fine-tuning", "p": "Gently adjusting a pretrained model's internals on your new data."},
    {"t": "Progressive fine-tuning", "p": "Doing that adjustment in stages — first the last layer, then more, then all of it — so you don't erase useful prior knowledge."},
    {"t": "Backbone", "p": "The main feature-extraction body of a neural network (e.g. ResNet50, Swin-Tiny)."},
    {"t": "FPN (Feature Pyramid Network)", "p": "A module that lets the model see fine details and big patterns at the same time."},
    {"t": "CNN", "p": "Convolutional Neural Network — uses small sliding filters to detect local patterns; great at textures."},
    {"t": "Transformer / self-attention", "p": "An architecture where every part of the image can look at every other part; better at general, transferable patterns."},
    {"t": "OA (Overall Accuracy)", "p": "The percentage of tiles the model labels correctly."},
    {"t": "F1 score", "p": "A balanced score (precision + recall) that's fairer than accuracy when classes are imbalanced."},
    {"t": "mIoU", "p": "Mean Intersection-over-Union — a stricter overlap measure between predicted and true classes."},
    {"t": "LOCO (Leave-One-City-Out)", "p": "Train on some cities, test on a completely unseen city — the real test of generalisation."},
    {"t": "In-distribution", "p": "Testing on the same kind of data (same cities) the model was trained on."},
    {"t": "Out-of-distribution (OOD)", "p": "Testing on different data (a new city) — usually much harder."},
    {"t": "Domain gap / shift", "p": "The accuracy you lose when a model meets data from a new place or time."},
    {"t": "Sentinel-2", "p": "A free European satellite, 10m per pixel, optical (visible + infrared)."},
    {"t": "Sentinel-1 / SAR", "p": "A free European radar satellite that can see through clouds."},
    {"t": "Landsat", "p": "NASA/USGS satellites, 30m per pixel, with imagery going back to the 1970s."},
    {"t": "GEE (Google Earth Engine)", "p": "A cloud platform for downloading and processing satellite imagery."},
    {"t": "ESA WorldCover", "p": "A free global 10m land-cover map we use as our 'answer key'."},
    {"t": "Weak supervision", "p": "Labels generated automatically (from another map), not hand-drawn by people."},
    {"t": "Transition class", "p": "Our new third class — a 100m band around city edges where pixels are half-built, half-not."},
    {"t": "Cross-entropy / Focal / Dice loss", "p": "Three 'scoring' functions the model minimises: standard, hard-example-focused, and rare-class-protecting."},
    {"t": "Bi-LSTM", "p": "A recurrent network that reads a time series both forwards and backwards."},
    {"t": "Attention (multi-head)", "p": "A mechanism that lets the model focus on the most important time steps."},
    {"t": "MC Dropout", "p": "Run the model ~50 times with random parts switched off; the spread of answers becomes a confidence band."},
    {"t": "95% confidence interval", "p": "The range the true value falls in 95% of the time — the forecast's error bars."},
    {"t": "SimCLR / self-supervised", "p": "Learning from unlabelled images by matching two augmented copies of the same image."},
    {"t": "GradCAM", "p": "A heatmap showing which pixels the model looked at to make its decision."},
    {"t": "Siamese network", "p": "Two identical networks comparing a before/after image pair to detect change."},
    {"t": "LEVIR-CD", "p": "A public before/after satellite dataset used to benchmark change detection."},
    {"t": "Ablation study", "p": "Removing one component at a time to see whether it actually helps."},
    {"t": "Seed", "p": "The random starting point of training; running 3 seeds checks results aren't a fluke."},
    {"t": "p < 0.05", "p": "Statistical significance — under a 5% chance the difference is random luck."},
    {"t": "CRZ", "p": "Coastal Regulation Zone — Indian law protecting the coastline."},
    {"t": "MoEFCC / CZMA", "p": "India's environment ministry / coastal-zone authority — where alerts get routed."},
    {"t": "NDVI / NDBI / NDWI", "p": "Spectral indices computed from satellite bands that highlight vegetation / built-up / water."},
    {"t": "PCA", "p": "Principal Component Analysis — compresses many features into a few while keeping the important information."},
]
